package http;

public enum Endpoint {
    POST_TASK,
    POST_UPDATE_TASK,
    GET_TASK_BY_ID,
    GET_ALL_TASKS,
    DELETE_TASK_BY_ID,
    DELETE_ALL_TASKS,
    HOST_SUBTASK,
    POST_SUBTASK,
    POST_UPDATE_SUBTASK,
    GET_SUBTASK_BY_ID,
    GET_ALL_SUBTASK,
    DELETE_SUBTASK_BY_ID,
    DELETE_ALL_SUBTASKS,
    POST_EPIC,
    POST_UPDATE_EPIC,
    GET_EPIC_BY_ID,
    GET_ALL_EPICS,
    DELETE_EPIC_BY_ID,
    DELETE_ALL_EPICS,
    GET_HISTORY,
    GET_PRIORITIZED_TASK,
    GET_EPIC_SUBTASKS,
    UNKNOWN
}
